// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpjIQ_Y_AWs3851WNk4cVOG2XcQceOlsQ',
    appId: '1:832204127664:android:ae768c545e43691660aa75',
    messagingSenderId: '832204127664',
    projectId: 'blue-draft-app-ec',
    storageBucket: 'blue-draft-app-ec.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIDqBvKLHcIiaZtsGLCaBQgBb93HMVsgM',
    appId: '1:832204127664:web:dc396fc40456d5ab60aa75',
    messagingSenderId: '832204127664',
    projectId: 'blue-draft-app-ec',
    authDomain: 'blue-draft-app-ec.firebaseapp.com',
    storageBucket: 'blue-draft-app-ec.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRO-sFz0J7vQMf7TLnFax3IaOXCP47p0g',
    appId: '1:832204127664:ios:2ff02cfce7d3bf5060aa75',
    messagingSenderId: '832204127664',
    projectId: 'blue-draft-app-ec',
    storageBucket: 'blue-draft-app-ec.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRO-sFz0J7vQMf7TLnFax3IaOXCP47p0g',
    appId: '1:832204127664:ios:2ff02cfce7d3bf5060aa75',
    messagingSenderId: '832204127664',
    projectId: 'blue-draft-app-ec',
    storageBucket: 'blue-draft-app-ec.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIDqBvKLHcIiaZtsGLCaBQgBb93HMVsgM',
    appId: '1:832204127664:web:1d7d824c86f794b460aa75',
    messagingSenderId: '832204127664',
    projectId: 'blue-draft-app-ec',
    authDomain: 'blue-draft-app-ec.firebaseapp.com',
    storageBucket: 'blue-draft-app-ec.firebasestorage.app',
  );

}